APPS_DICT = {'TV consoles': ['DuoPower',
  'Universal plug UX',
  'Universal plug UX Green',
  'Expansion plug SX',
  'Expansion plug SX Green',
  'Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head'],
 'Lighting': ['DuoPower',
  'Universal plug UX',
  'Universal plug UX Green',
  'Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug S',
  'Turbo aircrete anchor FTP K',
  'Plasterboard fixing GK',
  'Plasterboard fixing GK Green',
  'Board fixing PD',
  'Metal cavity fixing HM',
  'Plasterboard fixing metal GKM',
  'Board fixing GPF',
  'Board fixing HDF',
  'Nylon toggle K 54',
  'Toggle and spring fixing KD/KDH',
  'Scaffold eye screw GS GS 12 + plug',
  'Plug S 14 ROE',
  'Plug S 16 H R',
  'Scaffold eyebolt FI G 12',
  'Eye screw GS',
  'Plug S 12 R',
  'Plug S 14 H R',
  'Ring nut RI',
  'Stand-off installation TherMax 8',
  'Stand-off installation TherMax 10'],
 'Shelves': ['DuoPower',
  'DuoSeal',
  'Universal plug FU',
  'Turbo aircrete anchor FTP K',
  'Nylon toggle fischer DuoTec'],
 'Mirror cabinets': ['DuoPower',
  'Universal plug UX',
  'Universal plug UX Green',
  'Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug S',
  'Turbo aircrete anchor FTP K',
  'Board fixing PD',
  'Metal cavity fixing HM',
  'Toggle and spring fixing KD/KDH'],
 'Letter boxes': ['DuoPower',
  'Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug S',
  'Aircrete anchor GB',
  'Aircrete anchor GB Green',
  'Turbo aircrete anchor FTP K',
  'Stand-off installation TherMax 8',
  'Stand-off installation TherMax 10',
  'Injection mortar FIS Green'],
 'Pictures': ['DuoPower',
  'Universal plug UX',
  'Universal plug UX Green',
  'Expansion plug S',
  'Turbo aircrete anchor FTP K',
  'Frame fixing SXR with hook',
  'Plasterboard fixing DuoBlade',
  'Plasterboard fixing GK',
  'Plasterboard fixing GK Green',
  'Board fixing PD',
  'Metal cavity fixing HM',
  'Plasterboard fixing metal GKM',
  'Board fixing GPF',
  'Board fixing HDF',
  'Nylon toggle fischer DuoTec',
  'Nylon toggle K 54',
  'Toggle and spring fixing KD/KDH'],
 'Curtain rails': ['DuoPower',
  'Universal plug UX',
  'Universal plug UX Green',
  'Universal plug FU',
  'Expansion plug S',
  'Board fixing PD',
  'Metal cavity fixing HM'],
 'Wash basin fixings': ['DuoPower',
  'Universal plug UX',
  'Universal plug UX Green'],
 'Plumbing and heating fixings': ['DuoPower',
  'Universal plug UX',
  'Universal plug UX Green',
  'Threaded rod plug RodForce FGD'],
 'Bath and toilet installations': ['DuoPower',
  'Expansion plug SX',
  'Expansion plug SX Green'],
 'Wall cabinets': ['DuoPower', 'Frame fixing SXR with hook'],
 'Mirrors': ['DuoSeal',
  'Universal plug FU',
  'Frame fixing SXR with hook',
  'Plasterboard fixing DuoBlade',
  'Nylon toggle fischer DuoTec',
  'Nylon toggle K 54',
  'Sanitary fixing set WCN'],
 'Skirting': ['Universal plug UX',
  'Universal plug UX Green',
  'Universal plug FU',
  'Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug S',
  'ClassicFast FSP II CTF BC',
  'ClassicFast FSP II CZP BC',
  'ClassicFast FSP II CZF BC',
  'ClassicFast FSP II CZP YC',
  'ClassicFast FSP II CZF YC',
  'High Tack AC'],
 'Light cabinets': ['Universal plug UX',
  'Universal plug UX Green',
  'Toggle and spring fixing KD/KDH'],
 'Towel rails': ['Universal plug UX',
  'Universal plug UX Green',
  'Board fixing PD',
  'Metal cavity fixing HM',
  'Nylon toggle K 54',
  'Toggle and spring fixing KD/KDH'],
 'Electrical installations': ['Universal plug FU',
  'Expansion plug S',
  'Aircrete anchor GB Green',
  'Plasterboard fixing GK',
  'Plasterboard fixing GK Green',
  'Plasterboard fixing metal GKM',
  'Gas actuated fastening tool FGC 100'],
 'Mounting rails': ['Universal plug FU',
  'Threaded rod plug RodForce FGD',
  'Nail anchor FNA II',
  'Nail anchor FNA II RB',
  'Nail anchor FNA II M6 with thread and flange nut',
  'Nail anchor FNA II-H / FNA II-OE',
  'WC and sanitary fixing WL'],
 'Wardrobes': ['Expansion plug SX',
  'Expansion plug SX Green',
  'Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing SXR with hook',
  'Nylon toggle fischer DuoTec'],
 'Motion detectors': ['Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug S',
  'Turbo aircrete anchor FTP K',
  'Stand-off installation TherMax 8',
  'Stand-off installation TherMax 10'],
 'Light shelves': ['Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug S',
  'Board fixing PD',
  'Metal cavity fixing HM',
  'Nylon toggle K 54',
  'Toggle and spring fixing KD/KDH'],
 'Trellis': ['Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug M-S',
  'Aircrete anchor GB'],
 'Folding shutters': ['Expansion plug SX',
  'Expansion plug SX Green',
  'Expansion plug M-S'],
 'Suspension for individual pipes': ['Threaded rod plug RodForce FGD',
  'Concrete screw UltraCut FBS II 6 US',
  'Concrete screw UltraCut FBS II 6 SK',
  'Concrete screw UltraCut FBS II 6 P / LP',
  'Concrete screw UltraCut FBS II 6 M6 I, M8/M10 I',
  'Concrete screw UltraCut FBS II 6 M8/M10'],
 'Cable and pipe clips': ['Threaded rod plug RodForce FGD',
  'Turbo aircrete anchor FTP K',
  'Hammerfix N-S',
  'Hammerfix N Green',
  'Toggle and spring fixing KD/KDH'],
 'Consoles': ['Threaded rod plug RodForce FGD',
  'Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'High performance anchor FH II-I',
  'Sleeve anchor FSA-S',
  'Sleeve anchor FSA-B',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'Internal thread wall bolt (metric)',
  'Sleeve Anchor FSL',
  'Sleeve anchor FSL-B',
  'Sleeve anchor FSL-S',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-I',
  'ZYKON undercut anchor FZA-Q',
  'Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D',
  'Epoxy mortar FIS EB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS V Zero',
  'Injection mortar FIS VL',
  'Injection mortar FIS P',
  'WC and sanitary fixing WL',
  'Boiler fixing BO'],
 'Handles': ['Expansion plug M-S',
  'Aircrete anchor GB Green',
  'Sleeve Anchor FSL',
  'Sleeve anchor FSL-B',
  'Sleeve anchor FSL-S'],
 'Downpipes': ['Expansion plug M-S',
  'Stand-off installation TherMax 8',
  'Stand-off installation TherMax 10'],
 'Gratings': ['Expansion plug M-S',
  'Aircrete anchor GB Green',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Injection mortar FIS P Plus',
  'Injection mortar FIS P'],
 'Machines': ['Anchor M',
  'Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'High performance anchor FH II-I',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-I',
  'Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D',
  'Resin capsule RM II',
  'Injection mortar FIS HB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L'],
 'Pipelines': ['Aircrete anchor GB',
  'Aircrete anchor GB Green',
  'ZYKON hammerset anchor FZEA II',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Injection mortar FIS P'],
 'Guard rails': ['Aircrete anchor GB',
  'Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'Concrete screw UltraCut FBS II US',
  'Concrete screw UltraCut FBS II US R',
  'Concrete screw UltraCut FBS II CP US',
  'Concrete screw UltraCut FBS II SK',
  'Concrete screw UltraCut FBS II SK R',
  'Concrete screw UltraCut FBS II CP SK',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'High performance anchor FH II-I',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-I',
  'Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Resin capsule RSB',
  'Resin capsule RM II',
  'Injection mortar FIS HB',
  'Injection mortar FIS SB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS V Zero',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S',
  'Highbond anchor FHB II-A S Inject',
  'Zinc-alu spray FTC-ZA'],
 'Signs': ['Turbo aircrete anchor FTP K',
  'Wireclip WIC',
  'Wire cable WI',
  'Wire cable with eye and wireclip WIS',
  'Hammerfix N-P',
  'Stand-off installation TherMax 8',
  'Stand-off installation TherMax 10'],
 'Stand-off installations': ['Turbo aircrete anchor FTP K',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N'],
 'For use in load-bearing wooden constructions': ['PowerFast FPF II CZP BC',
  'PowerFast FPF II CZF BC'],
 'for the connection of solid wood parts as well as glued laminated timber': ['PowerFast FPF II CZP BC',
  'PowerFast FPF II CZF BC'],
 'cross laminated timber': ['PowerFast FPF II CZP BC',
  'PowerFast FPF II CZF BC'],
 'etc.': ['PowerFast FPF II CZP BC', 'PowerFast FPF II CZF BC'],
 'For metal parts to wood': ['PowerFast FPF II CZP BC',
  'PowerFast FPF II CZF BC'],
 'e.g. metal fittings': ['PowerFast FPF II CZP BC', 'PowerFast FPF II CZF BC'],
 'angles': ['PowerFast FPF II CZP BC', 'PowerFast FPF II CZF BC'],
 'beam shoes and other metal and wood connections.': ['PowerFast FPF II CZP BC',
  'PowerFast FPF II CZF BC'],
 'Suitable for use with fischer plugs and recommended loads.': ['PowerFast FPF II CZP BC',
  'PowerFast FPF II CZF BC'],
 'General wood joints': ['PowerFast FPF-SZ P',
  'PowerFast FPF-SZ F',
  'ClassicFast FSP II CTF BC',
  'ClassicFast FSP II CZP BC',
  'ClassicFast FSP II CZF BC',
  'ClassicFast FSP II CZP YC',
  'ClassicFast FSP II CZF YC'],
 'Safety-relevant applications': ['PowerFast FPF-SZ P',
  'PowerFast FPF-SZ F',
  'PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'Washer for construction screw with countersunk head',
  'PowerFull FPF-ST ZPF',
  'PowerFull FIF-ZT ZPF',
  'PowerFull FPF-ZTN ZPF'],
 'Plankings': ['PowerFast FPF-SZ P',
  'PowerFast FPF-SZ F',
  'ClassicFast FSP II CTF BC',
  'ClassicFast FSP II CZP BC',
  'ClassicFast FSP II CZF BC',
  'ClassicFast FSP II CZP YC',
  'ClassicFast FSP II CZF YC',
  'MDF screws PowerFast FDF-ST YZP'],
 'Door and metal fittings': ['PowerFast FPF-SZ P',
  'PowerFast FPF-SZ F',
  'ClassicFast FSP II CTF BC',
  'ClassicFast FSP II CZP BC',
  'ClassicFast FSP II CZF BC',
  'ClassicFast FSP II CZP YC',
  'ClassicFast FSP II CZF YC'],
 '': ['ClassicFast FSP II CTP BC',
  'Setting tool SZE',
  'Accessories',
  'Round cap MW / PS',
  'Closing plug (TermoZ SV II ecotwist)',
  'Cover caps',
  'Retaining disc without screw DHT',
  'Insulation discs DTM',
  'Accessories',
  'Checking gauge FUP',
  'Filling disc FFD',
  'Socket',
  'Washer',
  'Bits',
  'Accessories',
  'Accessories',
  'Accessories',
  'Accessories',
  'Stop drill EBB',
  'Setting tool EHS Plus',
  'Setting tool EA-ST',
  'Machine setting tool EMS',
  'Washer U',
  'Cover cap ADF',
  'Plasterboard fixing GK with drill bit tip',
  'Installation pliers HMZ',
  'Accessories TherMax 12/16',
  'Accessories for CAS compatible power tools',
  'Accessories for vacuum cleaner FVC 35 M',
  'Accessories for Direct Fastening',
  'Consumables for Direct Fastening',
  'Refrigeration pipe clamp FRS F',
  'Cover cap AK',
  'Cover cap FEC',
  'Flanged nut BUM',
  'PU dispensing gun',
  'PU-cleaner',
  'Application devices',
  'Mobile drilling eqiupment BSN 100',
  'Drill rig SBN 502',
  'Mobile drilling equipment LBT 80',
  'Manual drill head MB 2',
  'Mobile drilling equipment BSN 101T',
  'Side tables BST',
  'Machine accessories',
  'Testing and measuring equipment',
  'Setting tools',
  'Assembly tools',
  'Connection elements',
  'System accessories',
  'Thermal separation elements'],
 'Finger tightening elements': ['ClassicFast FSP II CTF BC',
  'ClassicFast FSP II CZP BC',
  'ClassicFast FSP II CZF BC',
  'ClassicFast FSP II CZP YC',
  'ClassicFast FSP II CZF YC',
  'Strap hinge screw FHT-SZ ZPF'],
 'Wooden fences': ['ClassicFast FSP II CTF BC',
  'ClassicFast FSP II CZP BC',
  'ClassicFast FSP II CZF BC',
  'ClassicFast FSP II CZP YC',
  'ClassicFast FSP II CZF YC'],
 'Typically used for wood-wood connections': ['ClassicFast FSP II CTF BC',
  'ClassicFast FSP II CZP BC',
  'ClassicFast FSP II CZF BC',
  'ClassicFast FSP II CZP YC',
  'ClassicFast FSP II CZF YC'],
 'Wood frame construction': ['PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'Washer for construction screw with countersunk head',
  'PowerFull FPF-ST ZPF',
  'PowerFull FIF-ZT ZPF',
  'PowerFull FPF-ZTN ZPF',
  'Gas actuated fastening tool FGW 90F'],
 'Post construction': ['PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'Washer for construction screw with countersunk head',
  'PowerFull FPF-ST ZPF',
  'PowerFull FIF-ZT ZPF',
  'PowerFull FPF-ZTN ZPF'],
 'Timber houses': ['PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'Washer for construction screw with countersunk head',
  'PowerFull FPF-ST ZPF',
  'PowerFull FIF-ZT ZPF',
  'PowerFull FPF-ZTN ZPF'],
 'Rooftop insulation systems': ['PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'PowerFull FPF-ST ZPF',
  'PowerFull FIF-ZT ZPF',
  'PowerFull FPF-ZTN ZPF'],
 'Car ports': ['PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'Washer for construction screw with countersunk head',
  'PowerFull FPF-ST ZPF',
  'PowerFull FIF-ZT ZPF',
  'PowerFull FPF-ZTN ZPF'],
 'Conservatories': ['PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'Washer for construction screw with countersunk head',
  'PowerFull FPF-ST ZPF',
  'PowerFull FIF-ZT ZPF',
  'PowerFull FPF-ZTN ZPF'],
 'Playground equipment': ['PowerFast FPF-ST ZPP',
  'PowerFast FPF-WT ZPP',
  'Washer for construction screw with countersunk head',
  'PowerFull FPF-ST ZPF',
  'PowerFull FPF-ZTN ZPF'],
 'Mounting of gypsum plasterboards on wooden posts': ['Drywall screw FSN-TPR',
  'Drywall screw belt-system FSN-TPRM',
  'FSN-TP',
  'FSN-TPM'],
 'Mounting of gypsum plasterboards on metal profiles': ['Drywall screw FSN-TPD',
  'Drywall screw belt-system FSN-TPDM',
  'Drywall screw FSN-TPB',
  'Drywall screw belt-system FSN-TPBM'],
 'Mounting of gypsum fibreboards (fermacell) on metal profiles': ['Gypsum fibreboard screws with HiLo thread (fermacell)',
  'Belt system gypsum fibreboard screws with HiLo thread FSN-TPGM (fermacell)'],
 'Connection of metal profiles in dry construction': ['Profile connection screw FSN-FP',
  'Profile connection screw FSN-FPB'],
 'Screwing of terrace plankings on wooden substructures': ['Terrace screw FTS-ST A2P',
  'Terrace screw FPF-ST A2P'],
 'Screwing of wood connectors': ['Flooring screws PowerFast FTF-ST YZP',
  'PowerFast FPF-PT ZPF'],
 'Flexible and rigid electric tubes': ['Locking clip SCN', 'Fastening tie FF'],
 'Flexible and rigid plastic insulating pipes': ['Pipe clip RC',
  'Pipe clip FC',
  'Saddle clip SCH',
  'Conduit clip BSM/BSMD/BSMZ',
  'Cable tie BN/GBN/UBN'],
 'Electric cables': ['Pipe clip FC',
  'Saddle clip SCH',
  'Fastening tie FF',
  'Spacer pipe clamp AM/AMD',
  'Cable harness SHA',
  'Cable tie BN/GBN/UBN'],
 'Steel conduits': ['Fastening tie FF',
  'Spacer pipe clamp AM/AMD',
  'Conduit clip BSM/BSMD/BSMZ',
  'Cable tie BN/GBN/UBN'],
 'Lighting strips': ['Wireclip WIC',
  'Wire cable WI',
  'Wire cable with eye and wireclip WIS'],
 'Cable trays': ['Wireclip WIC',
  'Wire cable WI',
  'Wire cable with eye and wireclip WIS',
  'Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'Concrete screw UltraCut FBS II 6 US',
  'Concrete screw UltraCut FBS II 6 SK',
  'Concrete screw UltraCut FBS II 6 P / LP',
  'Concrete screw UltraCut FBS II 6 M8/M10',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'High performance anchor FH II-I',
  'Sleeve anchor FSA-S',
  'Sleeve anchor FSA-B',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'Sleeve Anchor FSL',
  'Sleeve anchor FSL-B',
  'Sleeve anchor FSL-S',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-I',
  'ZYKON undercut anchor FZA-Q',
  'ZYKON hammerset anchor FZEA II',
  'Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Foam Barrier System PLUS',
  'Injection mortar FIS V Zero'],
 'Ventilation ducts': ['Wireclip WIC',
  'Wire cable WI',
  'Wire cable with eye and wireclip WIS',
  'Concrete screw UltraCut FBS II 6 US',
  'Concrete screw UltraCut FBS II 6 SK',
  'Concrete screw UltraCut FBS II 6 P / LP',
  'Concrete screw UltraCut FBS II 6 M6 I, M8/M10 I',
  'Concrete screw UltraCut FBS II 6 M8/M10'],
 'Pipes': ['Wireclip WIC',
  'Wire cable WI',
  'Wire cable with eye and wireclip WIS'],
 'Chilled ceilings': ['Wireclip WIC',
  'Wire cable WI',
  'Wire cable with eye and wireclip WIS'],
 'Busbars': ['Wire cable WI', 'Wire cable with eye and wireclip WIS'],
 'Attachment of ETICS insulating boards on concrete and masonry': ['TermoZ CNplus',
  'TermoZ CN 8',
  'TermoZ PN 8',
  'TermoZ CS II'],
 'e.g. polystyrene and mineral wool': ['TermoZ CNplus', 'TermoZ CNplus'],
 'Flush-to-surface installation in ETICS insulating materials e.g. polystyrene and mineral wool': ['TermoZ CN 8',
  'TermoZ PN 8'],
 'Flush installation in all conventional insulation materials': ['TermoZ CS II',
  'Render fixing FIF-CS 8'],
 'Used in combination with TermoZ': ['Additional plate DT',
  'Insulation discs DT'],
 'FIF and TermoFix anchors to fix ETICS insulating boards with low compressive strength.': ['Additional plate DT',
  'Insulation discs DT'],
 'Flush surface installation in ETICS insulating materials e.g. mineral wool.': ['Additional plate DT',
  'Insulation discs DT'],
 'Polystyrene boards': ['Render fixing DIPK', 'Insulation support DHM'],
 'Light building boards made of wood wool': ['Render fixing DIPK',
  'Insulation support DHK 45',
  'Insulation support DHK',
  'Insulation support DHM',
  'Retaining disc with screw DHT S'],
 'Cork boards / coir matting': ['Render fixing DIPK',
  'Insulation support DHK 45',
  'Insulation support DHK',
  'Retaining disc with screw DHT S'],
 'PU panels': ['Render fixing DIPK',
  'Insulation support DHK 45',
  'Insulation support DHK',
  'Retaining disc with screw DHT S',
  'Holding clamp DVN'],
 'Fixing of ETICS insulation boards on concrete and masonry': ['Render fixing FIF-CS 8',
  'Render fixing FIF-CN II 8',
  'Render fixing FIF-PN 8'],
 'Flush-to-surface installation in ETICS insulating materials e.g. polystyrene': ['Render fixing FIF-PN 8',
  'Screw fixing Termofix B'],
 'Mineral / glass wool': ['Insulation support DHK 45',
  'Insulation support DHK',
  'Insulation support DHM'],
 'Polystyrene': ['Insulation support DHK 45',
  'Insulation support DHK',
  'Retaining disc with screw DHT S',
  'Insulation fixing FID'],
 'Foam glass tiles': ['Insulation support DHK 45',
  'Insulation support DHK',
  'Insulation support DHM'],
 'Post-installed rebar connections': ['FIS-Rebar case',
  'Drilling aid',
  'Stocker',
  'Injection mortar FIS EM Plus',
  'Epoxy mortar FIS EB'],
 'Rebar connections': ['Brushes', 'Injection adapter'],
 'Robust and powerful all-rounder bits for the home': ['TX star recess ProfiBit',
  'PZ cross-slot ProfiBit',
  'PH cross-slot ProfiBit'],
 'crafts and trades': ['TX star recess ProfiBit',
  'PZ cross-slot ProfiBit',
  'PH cross-slot ProfiBit'],
 'and industry': ['TX star recess ProfiBit',
  'PZ cross-slot ProfiBit',
  'PH cross-slot ProfiBit'],
 'Primarily used for machine screw connections': ['TX star recess DiamondBit',
  'PH cross-slot DiamondBit'],
 'Steel constructions': ['Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'Concrete screw UltraCut FBS II US R',
  'Concrete screw UltraCut FBS II CP US',
  'Concrete screw UltraCut FBS II SK R',
  'Concrete screw UltraCut FBS II CP SK',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'High performance anchor FH II-I',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'ZYKON undercut anchor FZA-I',
  'ZYKON undercut anchor FZA-Q',
  'Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D',
  'Resin capsule RM II',
  'Highbond anchor FHB II-A L Inject',
  'Highbond anchor FHB II-A S Inject'],
 'Ladders': ['Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'High performance anchor FH II-I',
  'Sleeve anchor FSA-S',
  'Sleeve anchor FSA-B',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'Internal thread wall bolt (metric)',
  'Sleeve Anchor FSL',
  'Sleeve anchor FSL-B',
  'Sleeve anchor FSL-S',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-I'],
 'Staircases': ['Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'High performance anchor FH II-I',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'Internal thread wall bolt (metric)',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-I',
  'Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Resin capsule RSB',
  'Resin capsule RM II',
  'Injection mortar FIS HB',
  'Injection mortar FIS SB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S',
  'Highbond anchor FHB II-A L Inject',
  'Highbond anchor FHB II-A S Inject'],
 'Gates': ['Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'Sleeve anchor FSA-S',
  'Sleeve anchor FSA-B',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'Internal thread wall bolt (metric)',
  'Sleeve Anchor FSL',
  'Sleeve anchor FSL-B',
  'Sleeve anchor FSL-S',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-I',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Injection mortar FIS P Plus',
  'Injection mortar FIS P'],
 'Façades': ['Bolt anchor FAZ II',
  'Bolt anchor FBN II',
  'Bolt anchor EXA',
  'Bolt anchor EXA-IG',
  'Bolt anchor FWA',
  'Bolt anchor FWA (imperial)',
  'Bolt anchor FXA',
  'Concrete screw UltraCut FBS II US R',
  'Concrete screw UltraCut FBS II CP US',
  'Concrete screw UltraCut FBS II SK R',
  'Concrete screw UltraCut FBS II CP SK',
  'High performance anchor FH II-S',
  'High performance anchor FH II-SK',
  'High performance anchor FH II-H',
  'High performance anchor FH II-B',
  'Sleeve anchor FSA-S',
  'Sleeve anchor FSA-B',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'Sleeve Anchor FSL',
  'Sleeve anchor FSL-B',
  'Sleeve anchor FSL-S',
  'ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'ZYKON undercut anchor FZA-Q',
  'Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Injection mortar FIS HB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S',
  'Highbond anchor FHB II-A L Inject',
  'Highbond anchor FHB II-A S Inject'],
 'Timber constructions': ['Bolt anchor FAZ II',
  'Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Injection mortar FIS HB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S'],
 'FBN II': ['Setting tool FABS', 'Bolt anchor setting tool FA-ST II'],
 'Consoles/Base plates': ['Concrete screw UltraCut FBS II US',
  'Concrete screw UltraCut FBS II US R',
  'Concrete screw UltraCut FBS II CP US',
  'Concrete screw UltraCut FBS II SK',
  'Concrete screw UltraCut FBS II SK R',
  'Concrete screw UltraCut FBS II CP SK'],
 'Metal profiles': ['Concrete screw UltraCut FBS II US',
  'Concrete screw UltraCut FBS II US R',
  'Concrete screw UltraCut FBS II CP US',
  'Concrete screw UltraCut FBS II SK',
  'Concrete screw UltraCut FBS II SK R',
  'Concrete screw UltraCut FBS II CP SK',
  'Ceiling nail FDN II',
  'Nail sleeve FNH'],
 'Shelving systems': ['Concrete screw UltraCut FBS II US',
  'Cordless impact wrench FSS 18V 400 BL',
  'Cordless impact wrench FSS 18V 600'],
 'Protection barriers': ['Concrete screw UltraCut FBS II US',
  'Concrete screw UltraCut FBS II US R',
  'Concrete screw UltraCut FBS II CP US',
  'Concrete screw UltraCut FBS II SK R',
  'Concrete screw UltraCut FBS II CP SK'],
 'Shuttering props': ['Concrete screw UltraCut FBS II US',
  'Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D'],
 'Reinforcement of bridges': ['Concrete screw UltraCut FBS II US',
  'Concrete screw UltraCut FBS II SK'],
 'Rehabilitation of old and ailing buildings': ['Concrete screw UltraCut FBS II US',
  'Concrete screw UltraCut FBS II SK'],
 'Rehabilitation of car parks': ['Concrete screw UltraCut FBS II US',
  'Concrete screw UltraCut FBS II SK'],
 'Pipeline routes': ['Concrete screw UltraCut FBS II 6 US',
  'Concrete screw UltraCut FBS II 6 SK',
  'Concrete screw UltraCut FBS II 6 P / LP',
  'Concrete screw UltraCut FBS II 6 M6 I, M8/M10 I',
  'Concrete screw UltraCut FBS II 6 M8/M10',
  'High performance anchor FH II-I',
  'Cordless impact wrench FSS 18V 400 BL',
  'Cordless impact wrench FSS 18V 600'],
 'Suspended mounting rails': ['Concrete screw UltraCut FBS II 6 US',
  'Concrete screw UltraCut FBS II 6 SK',
  'Concrete screw UltraCut FBS II 6 P / LP',
  'Concrete screw UltraCut FBS II 6 M6 I, M8/M10 I',
  'Concrete screw UltraCut FBS II 6 M8/M10'],
 'Prestressed concrete hollow core ceilings': ['Concrete screw UltraCut FBS II 6 US',
  'Concrete screw UltraCut FBS II 6 SK',
  'Concrete screw UltraCut FBS II 6 P / LP',
  'Concrete screw UltraCut FBS II 6 M6 I, M8/M10 I',
  'Concrete screw UltraCut FBS II 6 M8/M10'],
 'Perforated tapes': ['Concrete screw UltraCut FBS II 6 US',
  'Concrete screw UltraCut FBS II 6 SK',
  'Concrete screw UltraCut FBS II 6 P / LP',
  'Concrete screw UltraCut FBS II 6 M8/M10',
  'Ceiling nail FDN II',
  'Hammerfix N-S',
  'Hammerfix N Green'],
 'Ventilation systems': ['High performance anchor FH II-I',
  'ZYKON hammerset anchor FZEA II',
  'Nail anchor FNA II',
  'Nail anchor FNA II RB',
  'Nail anchor FNA II M6 with thread and flange nut',
  'Nail anchor FNA II-H / FNA II-OE',
  'Ceiling nail FDN II'],
 'Sprinkler systems': ['High performance anchor FH II-I',
  'ZYKON hammerset anchor FZEA II',
  'Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D'],
 'Handrails': ['Sleeve anchor FSA-S',
  'Sleeve anchor FSA-B',
  'Heavy-duty anchor TA M',
  'Heavy-duty anchor TA M-S',
  'Heavy-duty anchor SL M/SLM-N',
  'Nylon toggle fischer DuoTec',
  'Injection mortar FIS V Zero',
  'Injection mortar FIS P Plus',
  'Injection mortar FIS P'],
 'Temporary or structural fixings': ['Sleeve anchor FSA-S',
  'Sleeve anchor FSA-B',
  'Sleeve Anchor FSL',
  'Sleeve anchor FSL-B',
  'Sleeve anchor FSL-S'],
 'Steelwork constructions': ['ZYKON undercut anchor FZA',
  'ZYKON Through anchor FZA-D',
  'Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Injection mortar FIS HB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS V Zero',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S'],
 'Fire protection plates': ['Nail anchor FNA II',
  'Nail anchor FNA II RB',
  'Nail anchor FNA II M6 with thread and flange nut',
  'Nail anchor FNA II-H / FNA II-OE'],
 'Fire protection boards': ['Nail anchor FNA II',
  'Nail anchor FNA II RB',
  'Nail anchor FNA II M6 with thread and flange nut',
  'Nail anchor FNA II-H / FNA II-OE'],
 'Metal clamps': ['Nail anchor FNA II',
  'Nail anchor FNA II RB',
  'Nail anchor FNA II M6 with thread and flange nut',
  'Nail anchor FNA II-H / FNA II-OE'],
 'Substructures made of wood and metal': ['Nail anchor FNA II',
  'Nail anchor FNA II RB',
  'Nail anchor FNA II M6 with thread and flange nut',
  'Nail anchor FNA II-H / FNA II-OE',
  'Hammerfix N Green',
  'Nail sleeve FNH',
  'High Tack MS'],
 'Wire and Nonius hangers': ['Nail anchor FNA II RB',
  'Nail anchor FNA II M6 with thread and flange nut',
  'Nail anchor FNA II-H / FNA II-OE',
  'Ceiling nail FDN II'],
 'Pipelines and ventilation ducts': ['Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D'],
 'Cable conduits and wires': ['Hammerset anchor EA II',
  'Hammerset anchor EA N-D / EA II-D'],
 'Facade': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw'],
 'ceiling and roof substructures made of wood and metal': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing FUR with countersunk head',
  'Frame fixing FUR with hexagon head',
  'Frame fixing S-H-R - without screw',
  'Frame fixing S-H-R - hexagonal screw'],
 'Windows': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing FUR with countersunk head',
  'Frame fixing FUR with hexagon head',
  'Frame fixing S-H-R - without screw',
  'Frame fixing S-H-R - hexagonal screw'],
 'Gates and doors': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing FUR with countersunk head',
  'Frame fixing FUR with hexagon head',
  'Frame fixing S-H-R - without screw',
  'Frame fixing S-H-R - hexagonal screw'],
 'Kitchen hanging cabinets': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Nylon toggle fischer DuoTec'],
 'Squared timbers': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing FUR with countersunk head',
  'Frame fixing FUR with hexagon head',
  'Frame fixing S-H-R - without screw',
  'Frame fixing S-H-R - hexagonal screw',
  'Nail sleeve FNH',
  'Metal frame fixing F-M',
  'Window frame screws FFS',
  'Window frame screws FFSZ'],
 'Beams': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing FUR with countersunk head',
  'Frame fixing FUR with hexagon head',
  'Frame fixing S-H-R - without screw',
  'Frame fixing S-H-R - hexagonal screw',
  'Epoxy mortar FIS EP'],
 'Wall covering': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing FUR with countersunk head',
  'Frame fixing FUR with hexagon head'],
 'Metal brackets': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head'],
 'Metal supports': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head'],
 'Cable ducts': ['Frame fixing DuoXpand with countersunk head screw',
  'Frame fixing DuoXpand with hexagon head screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'High Tack AC',
  'Express PU'],
 'Façade': ['Frame fixing SXRL without safety screw',
  'Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw',
  'Frame fixing SXR without safety screw',
  'Frame fixing SXR with countersunk head',
  'Frame fixing SXR with hexagon head',
  'Frame fixing FUR with countersunk head',
  'Frame fixing FUR with hexagon head',
  'Frame fixing S-H-R - without screw',
  'Frame fixing S-H-R - hexagonal screw'],
 'Facade substructures under compression load (e.g. distance installation without a wall bracket)': ['Frame fixing SXRL with countersunk head screw',
  'Frame fixing SXRL with hexagon head screw'],
 'Wall connection or plaster profiles': ['Hammerfix N-S', 'Hammerfix N Green'],
 'Metal constructions': ['Hammerfix N-F', 'Zinc-alu spray FTC-ZA'],
 'Slides': ['Hammerfix N-P', 'Hammerfix N Green'],
 'Sheets': ['Hammerfix N-P', 'Hammerfix N-S D', 'Hammerfix N Green'],
 'Mounting in the viewing area': ['Hammerfix N-P', 'Hammerfix N-S D'],
 'Lamps': ['Plasterboard fixing DuoBlade', 'Nylon toggle fischer DuoTec'],
 'Fitting accessories': ['Plasterboard fixing GK',
  'Plasterboard fixing GK Green',
  'Plasterboard fixing metal GKM'],
 'Series installations': ['Plasterboard fixing GK',
  'Plasterboard fixing GK Green'],
 'Light-weight sanitary equipment': ['Board fixing GPF', 'Board fixing HDF'],
 'Façade scaffolds': ['Scaffold eye screw GS GS 12 + plug',
  'Plug S 14 ROE',
  'Plug S 16 H R',
  'Scaffold eyebolt FI G 12'],
 'Ropes': ['Scaffold eye screw GS GS 12 + plug',
  'Plug S 14 ROE',
  'Plug S 16 H R',
  'Eye screw GS',
  'Plug S 12 R',
  'Plug S 14 H R',
  'Ring nut RI'],
 'Chains': ['Scaffold eye screw GS GS 12 + plug',
  'Plug S 14 ROE',
  'Plug S 16 H R',
  'Scaffold eyebolt FI G 12',
  'Eye screw GS',
  'Plug S 12 R',
  'Plug S 14 H R',
  'Ring nut RI'],
 'Trellises': ['Scaffold eye screw GS GS 12 + plug',
  'Plug S 14 ROE',
  'Plug S 16 H R',
  'Scaffold eyebolt FI G 12',
  'Eye screw GS',
  'Plug S 12 R',
  'Plug S 14 H R',
  'Ring nut RI'],
 'Clothes lines': ['Scaffold eye screw GS GS 12 + plug',
  'Plug S 14 ROE',
  'Plug S 16 H R',
  'Scaffold eyebolt FI G 12',
  'Eye screw GS',
  'Plug S 12 R',
  'Plug S 14 H R',
  'Ring nut RI'],
 'Hanging baskets': ['Scaffold eye screw GS GS 12 + plug',
  'Plug S 14 ROE',
  'Plug S 16 H R',
  'Scaffold eyebolt FI G 12',
  'Eye screw GS',
  'Plug S 12 R',
  'Plug S 14 H R',
  'Ring nut RI'],
 'Lightning rods': ['Stand-off installation TherMax 8',
  'Stand-off installation TherMax 10'],
 'Blind guide rails': ['Stand-off installation TherMax 8',
  'Stand-off installation TherMax 10'],
 'Awnings': ['Stand-off installation TherMax 12',
  'Stand-off installation TherMax 16',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Injection mortar FIS P Plus'],
 'Canopies': ['Stand-off installation TherMax 12',
  'Stand-off installation TherMax 16',
  'Cordless impact wrench FSS 18V 400 BL',
  'Cordless impact wrench FSS 18V 600',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS V Zero',
  'Injection mortar FIS VL',
  'Injection mortar FIS P Plus'],
 'French balcony railings': ['Stand-off installation TherMax 12',
  'Stand-off installation TherMax 16'],
 'Air conditioning units': ['Stand-off installation TherMax 12',
  'Stand-off installation TherMax 16'],
 'Satellite dishes': ['Stand-off installation TherMax 12',
  'Stand-off installation TherMax 16'],
 'Anchoring of railings': ['Cordless impact wrench FSS 18V 400 BL',
  'Cordless impact wrench FSS 18V 600'],
 'Column bases': ['Cordless impact wrench FSS 18V 400 BL',
  'Cordless impact wrench FSS 18V 600',
  'Resin capsule RM II'],
 'Steel-steel connections': ['Cordless impact wrench FSS 18V 400 BL',
  'Cordless impact wrench FSS 18V 600'],
 'Tyre changes': ['Cordless impact wrench FSS 18V 400 BL',
  'Cordless impact wrench FSS 18V 600'],
 'Steel brackets': ['Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Injection mortar FIS HB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S'],
 'Masts': ['Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Resin capsule RM II',
  'Injection mortar FIS HB',
  'Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS VL',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S',
  'Highbond anchor FHB II-A L Inject',
  'Highbond anchor FHB II-A S Inject'],
 'Rash protection': ['Resin capsule FHB II-P / FHB II-PF HIGH SPEED',
  'Injection mortar FIS HB',
  'Highbond anchor FHB II-A L',
  'Highbond anchor FHB II-A S'],
 'Heavy steel constructions': ['Resin capsule RSB',
  'Injection mortar FIS SB',
  'Injection mortar FIS EM Plus',
  'Epoxy mortar FIS EB'],
 'Silo installations': ['Resin capsule RSB',
  'Injection mortar FIS HB',
  'Injection mortar FIS SB',
  'Injection mortar FIS EM Plus',
  'Epoxy mortar FIS EB',
  'Highbond anchor FHB II-A L'],
 'Tall shelving': ['Resin capsule RSB',
  'Injection mortar FIS SB',
  'Injection mortar FIS EM Plus',
  'Epoxy mortar FIS EB'],
 'Sound barriers': ['Resin capsule RSB',
  'Injection mortar FIS SB',
  'Injection mortar FIS EM Plus'],
 'Temporary fixings': ['Resin capsule RM II', 'Injection mortar FIS SB'],
 'e.g. for machines': ['Resin capsule RM II', 'Injection mortar FIS SB'],
 'Scaffold anchoring': ['Resin capsule RM II', 'Injection mortar FIS SB'],
 'Overhead installations': ['Resin capsule RM II', 'Centring wedges'],
 'Satellite antennas': ['Injection mortar FIS V Plus',
  'Injection mortar FIS V, FIS VS LOW SPEED, FIS VW HIGH SPEED',
  'Injection mortar FIS V Zero',
  'Injection mortar FIS VL'],
 'Anchorings with injection mortars FIS SB': ['Threaded rod RG M',
  'Internal-threaded anchor RG M I'],
 'FIS EB': ['Threaded rod RG M', 'Threaded rod FIS A'],
 'FIS V': ['Threaded rod RG M',
  'Threaded rod FIS A',
  'Internal-threaded anchor RG M I'],
 'FIS VL': ['Threaded rod RG M',
  'Threaded rod FIS A',
  'Internal-threaded anchor RG M I',
  'Internal threaded sockets FIS E',
  'Injections anchor sleeve FIS H K',
  'Injection anchor sleeve, 1 m length FIS H L',
  'Injection anchor sleeve with net FIS H N'],
 'FIS P Plus': ['Threaded rod RG M',
  'Threaded rod FIS A',
  'Internal threaded sockets FIS E',
  'Injections anchor sleeve FIS H K',
  'Injection anchor sleeve, 1 m length FIS H L',
  'Injection anchor sleeve with net FIS H N'],
 'FIS P': ['Threaded rod RG M',
  'Threaded rod FIS A',
  'Internal threaded sockets FIS E',
  'Injections anchor sleeve FIS H K',
  'Injection anchor sleeve, 1 m length FIS H L',
  'Injection anchor sleeve with net FIS H N'],
 'and FIS Green': ['Threaded rod RG M',
  'Threaded rod FIS A',
  'Injections anchor sleeve FIS H K'],
 'Anchorings with injection mortars without approval': ['Threaded rod FTR',
  'Threaded rod FIS GS'],
 'FIS EM Plus': ['Threaded rod FIS A', 'Internal-threaded anchor RG M I'],
 'Removable and temporary fixings': ['Internal-threaded anchor RG M I',
  'Internal threaded sockets FIS E'],
 'Guide rails for elevators': ['Highbond-Anchor dynamic FHB dyn',
  'Dynamic-anchor FDA',
  'Filling sets'],
 'Industrial robots': ['Highbond-Anchor dynamic FHB dyn',
  'Dynamic-anchor FDA',
  'Filling sets'],
 'Conveyor belts': ['Dynamic-anchor FDA', 'Filling sets'],
 'Anchorings in perforated brick masonry with injection mortars FIS V': ['Injections anchor sleeve FIS H K',
  'Injection anchor sleeve, 1 m length FIS H L',
  'Injection anchor sleeve with net FIS H N'],
 'and FIS Green without approval': ['Injection anchor sleeve, 1 m length FIS H L',
  'Injection anchor sleeve with net FIS H N'],
 'Cleaning of drill holes': ['Blow-out pump',
  'Brushes for concrete (& masonry)'],
 'Energy-saving injection cartridge dispensing': ['Dispenser, manual',
  'Dispenser, pneumatic'],
 'For simple and easy fixing of pipelines with threaded rods or hanger bolts': ['Pipe clamp FRS Triple',
  'Pipe clamp FRSN Triple'],
 'Fixing of medium to heavy pipes with threaded rods (hanger bolts)': ['Heavy duty pipe clamp FRSM - inch',
  'Heavy duty pipe clamp FRSM - metric'],
 'Installation of sprinkler pipes': ['Sprinkler clamp FRSP',
  'Sprinkler clamp FCHS'],
 'Used for the suspension of stationary': ['Sprinkler clamp FRSP',
  'Sprinkler clamp FCHS'],
 'non-insulated pipelines': ['Sprinkler clamp FRSP', 'Sprinkler clamp FCHS'],
 'Connecting elements for the arrangement of simple channel constructions with the sliding channel nut FSM Clix P.': ['Angle bracket MW',
  'Angle bracket MWU'],
 'Connection of pipe clamps to the channel': ['T-head bolt FHS Clix S',
  'T-head bolt FCSN'],
 'Arrangement of simple channel constructions in the push-through system': ['Bracket PFFF',
  'Bracket PFAF'],
 'Free-standing toilets': ['Sanitary fixing set WCN',
  'Sanitary fixing set S 8 D 70 WCR',
  'Sanitary fixing set S 8 RD WCR'],
 'Bidets': ['Sanitary fixing set WCN',
  'Sanitary fixing set S 8 D 70 WCR',
  'Sanitary fixing set S 8 RD WCR'],
 'Wash basins': ['Wash basin and urinal fixing WD',
  'Wash basin and urinal fixing for panel building materials WDP',
  'Wash basin fixing WST'],
 'Urinals': ['Wash basin and urinal fixing WD',
  'Wash basin and urinal fixing for panel building materials WDP',
  'Wash basin fixing WST',
  'Urinal fixing UST'],
 'Built-in toilets': ['Wash basin and urinal fixing WD',
  'Wash basin and urinal fixing for panel building materials WDP',
  'Wash basin fixing WST',
  'Urinal fixing UST'],
 'Cisterns': ['Wash basin and urinal fixing WD',
  'Wash basin and urinal fixing for panel building materials WDP',
  'Wash basin fixing WST',
  'Boiler fixing BO'],
 'Gas heaters': ['WC and sanitary fixing WL', 'Boiler fixing BO'],
 'Window frames': ['Window frame fixing F-S', 'Metal frame fixing F-M'],
 'Door frames': ['Window frame fixing F-S',
  'Metal frame fixing F-M',
  'Window frame screws FFS',
  'Window frame screws FFSZ'],
 'Window frames made of wood': ['Window frame screws FFS',
  'Window frame screws FFSZ'],
 'plastic and aluminium': ['Window frame screws FFS',
  'Window frame screws FFSZ'],
 'Insulating and filling in roofing work and dry construction': ['1c premium installation foam PU 500/750',
  '1c premium gun foam PUP 750 B3'],
 'Insulating and filling window connection joints': ['1c premium installation foam PU 500/750',
  '1c premium gun foam compact PUP 500 B2',
  '1c gun foam PUP S 750 B2',
  '1c premium gun foam PUP 750 B3',
  '1c Premium gun foam PUP B1 750'],
 'around window sills and shutter boxes': ['1c premium installation foam PU 500/750',
  '1c premium gun foam compact PUP 500 B2',
  '1c gun foam PUP S 750 B2',
  '1c premium gun foam PUP 750 B3',
  '1c Premium gun foam PUP B1 750'],
 'Insulating and filling finished elements': ['1c premium installation foam PU 500/750',
  '1c premium gun foam PUP 750 B3',
  '1c Premium gun foam PUP B1 750'],
 'wall connections and wall penetrations': ['1c premium installation foam PU 500/750',
  '1c premium gun foam compact PUP 500 B2'],
 'Insulating and filling pipe penetrations and ventilation ducts': ['1c premium gun foam compact PUP 500 B2',
  '1c premium gun foam PUP 750 B3'],
 'To insulate and fill wall penetrations': ['1c gun foam PUP S 750 B2',
  '1c premium gun foam PUP BS 750 B2'],
 'cavities': ['1c gun foam PUP S 750 B2', '1c premium gun foam PUP BS 750 B2'],
 'wall connections and finished elements': ['1c gun foam PUP S 750 B2',
  '1c premium gun foam PUP BS 750 B2'],
 'To seal and bind well shafts': ['1c gun foam PUP S 750 B2',
  '1c premium gun foam PUP BS 750 B2'],
 'manhole shafts': ['1c gun foam PUP S 750 B2',
  '1c premium gun foam PUP BS 750 B2'],
 'domestic sewage treatment plants and cisterns': ['1c gun foam PUP S 750 B2',
  '1c premium gun foam PUP BS 750 B2'],
 'wall connections': ['1c premium gun foam PUP 750 B3',
  '1c Premium gun foam PUP B1 750'],
 'wall penetrations and cavities': ['1c premium gun foam PUP 750 B3',
  '1c Premium gun foam PUP B1 750'],
 'Connection joints in the kitchen': ['Premium sanitary silicone DSSA',
  'Sanitary silicone DSSI',
  'Multi-silicone DMS'],
 'Seal welds for display cabinets and glass blocks': ['Premium sanitary silicone DSSA',
  'Sanitary silicone DSSI',
  'Multi-silicone DMS'],
 'Joints in sinks and toilets': ['Sanitary silicone DSSI',
  'Multi-silicone DMS'],
 'Expansion joints between floor and wall tiles': ['Sanitary silicone DSSI',
  'Multi-silicone DMS'],
 'Joints around enamel and plastic showers and bath tubs': ['Sanitary silicone DSSI',
  'Multi-silicone DMS'],
 'Connection joints between timber and tiles': ['Sanitary silicone DSSI',
  'Multi-silicone DMS'],
 'Glazing wood and aluminium windows': ['Sanitary silicone DSSI',
  'Multi-silicone DMS'],
 'Connection and expansion joints in the construction industry (e.g. windows': ['Premium construction silicone DBSA',
  'Roof and wall silicone DBSI'],
 'doors': ['Premium construction silicone DBSA',
  'Roof and wall silicone DBSI',
  'Acrylic sealant standard DA'],
 'façades': ['Premium construction silicone DBSA',
  'Roof and wall silicone DBSI'],
 'light domes)': ['Premium construction silicone DBSA',
  'Roof and wall silicone DBSI'],
 'Movement and connection joints in kitchens': ['Premium construction silicone DBSA',
  'Roof and wall silicone DBSI'],
 'sanitary areas and installations': ['Premium construction silicone DBSA',
  'Roof and wall silicone DBSI'],
 'Joints between walls and ceilings': ['Premium painting acrylic DMA',
  'Premium structured acrylic DSA'],
 'Joints in dry and internal construction': ['Premium painting acrylic DMA',
  'Premium structured acrylic DSA'],
 'Connection joints with low movement': ['Premium structured acrylic DSA',
  'Acrylic sealant standard DA'],
 'Grouting roof penetrations such as chimneys or light domes': ['Premium all-weather sealant DDK',
  'Roof sealing compound DD'],
 'as well as edge connections': ['Premium all-weather sealant DDK',
  'Roof sealing compound DD'],
 'Sealing of metal and plastic gutters': ['Premium all-weather sealant DDK',
  'Roof sealing compound DD'],
 'Sealings around antennas and ventilation ducts': ['Premium all-weather sealant DDK',
  'Roof sealing compound DD'],
 'Décorative': ['High Tack AC', 'Express PU'],
 'acoustic and insulation panels': ['High Tack AC', 'Express PU'],
 'Tiles': ['High Tack AC', 'Glass drill bit D-GT', 'Diamond hole saw HS-DI'],
 'Door signs': ['High Tack AC', 'Express PU'],
 'Repairing damaged zinc coatings': ['Zinc spray FTC-ZS',
  'Zinc-alu spray FTC-ZA'],
 'Reinforced concrete': ['Hammer drill bit Quattric II',
  'Hollow drill bit FHD'],
 'Concrete': ['Hammer drill bit Quattric II',
  'Hammer drill bit SDS Plus II Pointer',
  'Hammer drill bit SDS Max II / SDS Max IV',
  'Hollow drill bit FHD',
  'Concrete drill bit D-C',
  'Premium chisel FCP'],
 'Solid brick': ['Hammer drill bit Quattric II',
  'Hammer drill bit SDS Plus II Pointer',
  'Hammer drill bit SDS Max II / SDS Max IV',
  'Hollow drill bit FHD'],
 'Sand-lime brick': ['Hammer drill bit Quattric II',
  'Hammer drill bit SDS Plus II Pointer',
  'Hammer drill bit SDS Max II / SDS Max IV',
  'Concrete drill bit D-C',
  'Stone drill bit D-S',
  'Stone drill bit D-SDX'],
 'Natural stone': ['Hammer drill bit Quattric II',
  'Hammer drill bit SDS Plus II Pointer',
  'Hammer drill bit SDS Max II / SDS Max IV',
  'Hollow drill bit FHD',
  'Concrete drill bit D-C',
  'Stone drill bit D-S',
  'Premium chisel FCP'],
 'Aerated concrete': ['Masonry drill bit Pointer M',
  'Concrete drill bit D-C',
  'Stone drill bit D-S',
  'Stone drill bit D-SDX',
  'Multi-hole saw HS-Multi'],
 'Masonry': ['Concrete drill bit D-C',
  'Stone drill bit D-S',
  'Stone drill bit D-SDX',
  'Premium chisel FCP'],
 'Gypsum plasterboard': ['Concrete drill bit D-C',
  'Stone drill bit D-S',
  'Stone drill bit D-SDX',
  'Multi-hole saw HS-Multi'],
 'Wooden materials': ['Wood drill bit D-WS', 'Auger bit D-WL'],
 'Wood and panel building materials': ['Wood drill bit D-WS',
  'Auger bit D-WL',
  'Forstner drill bit D-WFo'],
 'Hard wood (e.g. beech': ['Wood drill bit D-WS',
  'Auger bit D-WL',
  'Forstner drill bit D-WFo',
  'Multi-hole saw HS-Multi'],
 'oak': ['Wood drill bit D-WS',
  'Auger bit D-WL',
  'Forstner drill bit D-WFo',
  'Multi-hole saw HS-Multi'],
 'etc.)': ['Wood drill bit D-WS',
  'Auger bit D-WL',
  'Forstner drill bit D-WFo',
  'Multi-hole saw HS-Multi'],
 'Wooden beams': ['Wood drill bit D-WS',
  'Auger bit D-WL',
  'Forstner drill bit D-WFo'],
 'Soft woods': ['Wood drill bit D-WS',
  'Auger bit D-WL',
  'Forstner drill bit D-WFo',
  'Multi-hole saw HS-Multi'],
 'Plastics': ['Wood drill bit D-WS',
  'Bi-metal hole saw HS-HSS-Co',
  'Multi-hole saw HS-Multi'],
 'Glass': ['Glass drill bit D-GT', 'Diamond hole saw HS-DI'],
 'Stainless steel': ['Metal drill bit D-HSS-Co',
  'Bi-metal hole saw HS-HSS-Co'],
 'Brass': ['Metal drill bit D-HSS-G', 'Metal drill bit D-HSS-R'],
 'Steel 900 N/mm²': ['Metal drill bit D-HSS-G', 'Metal drill bit D-HSS-R'],
 'Cast steel alloyed and unalloyed': ['Metal drill bit D-HSS-G',
  'Metal drill bit D-HSS-R'],
 'Grey cast iron': ['Metal drill bit D-HSS-G', 'Metal drill bit D-HSS-R'],
 'Malleable cast iron': ['Metal drill bit D-HSS-G', 'Metal drill bit D-HSS-R'],
 'Sinter iron': ['Metal drill bit D-HSS-G', 'Metal drill bit D-HSS-R'],
 'Spheroidal graphite iron': ['Metal drill bit D-HSS-G',
  'Metal drill bit D-HSS-R'],
 'Graphite': ['Metal drill bit D-HSS-G', 'Metal drill bit D-HSS-R'],
 'Bronze': ['Metal drill bit D-HSS-G', 'Metal drill bit D-HSS-R'],
 'Aluminium short chipping': ['Metal drill bit D-HSS-G',
  'Metal drill bit D-HSS-R'],
 'Material and surface finishing': ['Premium chisel FCP Max',
  'Standard chisel SDS Plus',
  'Standard chisel SDS Max'],
 'Creating holes': ['Premium chisel FCP Max',
  'Standard chisel SDS Plus',
  'Standard chisel SDS Max'],
 'slots and installation paths': ['Premium chisel FCP Max',
  'Standard chisel SDS Plus',
  'Standard chisel SDS Max'],
 'Exterior façades': ['Zykon-Panel anchor FZP II A4',
  'Zykon-Panel anchor FZP II Carbon',
  'Zykon-Panel anchor FZP II M8i',
  'Zykon-Panel anchor FZP II T Tergo+',
  'Zykon-Panel anchor FZP II T PA',
  'Zykon-Glas point fixing FZP G Z ESG',
  'Zykon-Glas point fixing FZP G Z VSG',
  'Undercut drill bits',
  'Undercut drill bit glass',
  'Undercut drill bits CNC'],
 'Interior façades': ['Zykon-Panel anchor FZP II A4',
  'Zykon-Panel anchor FZP II Carbon',
  'Zykon-Panel anchor FZP II M8i',
  'Zykon-Panel anchor FZP II T Tergo+',
  'Zykon-Panel anchor FZP II T PA',
  'Zykon-Glas point fixing FZP G Z ESG',
  'Zykon-Glas point fixing FZP G Z VSG',
  'Undercut drill bits',
  'Undercut drill bit glass',
  'Undercut drill bits CNC'],
 'Façade reveals': ['Zykon-Panel anchor FZP II A4',
  'Zykon-Panel anchor FZP II Carbon',
  'Zykon-Panel anchor FZP II M8i',
  'Zykon-Panel anchor FZP II T Tergo+',
  'Zykon-Panel anchor FZP II T PA',
  'Undercut drill bits',
  'Undercut drill bits CNC'],
 'Natural stone heating systems': ['Zykon-Panel anchor FZP II A4',
  'Zykon-Panel anchor FZP II Carbon'],
 'Exterior façades with high aesthetic requirements': ['Zykon-Panel anchor FZP II SO AL',
  'Zykon-Panel anchor FZP II SO Carbon'],
 'Interior façades with high aesthetic requirements': ['Zykon-Panel anchor FZP II SO AL',
  'Zykon-Panel anchor FZP II SO Carbon'],
 'soft natural stone (stone group IV - sedimentary rock)': ['Zykon-Panel anchor FZP II SH',
  'Zykon-Panel anchor FZP II SH'],
 'Glass façades': ['Zykon-Glas point fixing FZP G Z ESG',
  'Zykon-Glas point fixing FZP G Z VSG',
  'Undercut drill bit glass'],
}